name: Run Python Script Every Minute

on:
  schedule:
    # Runs every minute for testing purposes
    - cron: '*/1 * * * *'  # This cron schedule runs every minute

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python script
      run: |
        python script/fetchPrices.py